### PR TITLE
Improve fee handling

### PR DESCRIPTION
**Pull request by luckysori**

### CODE REVIEW

**Review by holzeis — APPROVED** [review]
LGTM 👍 

However, it would probably be worthwhile if @bonomat could also have a look.

**Comment by luckysori** [comment]
I will merge it for now, but please do have a look if you find time, @bonomat.

**Comment by luckysori** [comment]
> I will merge it for now, but please do have a look if you find time, @bonomat.

Actually, I won't merge it yet because `master` includes breaking changes that I don't want to use in 10101 just yet. I've cherry-picked a couple of patches from `master`. I will update https://github.com/get10101/10101/pull/2062 to depend on this branch.

**Comment by luckysori** [comment]
Forgot to merge. This is already being used in 10101.

**Pull request merged**
